name: Build, Test, and Publish!!!

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
        -main
  workflow_dispatch:

jobs:
  build-test-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - run: |
          /bin/bash run.sh install
          /bin/bash run.sh build
          /bin/bash run.sh publish:test
        # env:
        #     TEST_PYPI_TOKEN: ${{ secrets.}}


  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump secrets
        env:
          SECRETS: ${{ toJson(secrets) }}
        run: echo "$SECRETS"
      - name: Dump variables
        env:
          VARIABLES: ${{ toJson(vars) }}
        run: echo "$VARIABLES"
